package dpfm_api_output_formatter

func ConvertToGoogleAccountUserInfoRequestsFromResponse(
	googleAccountUserInfoRequestsResponseBody GoogleAccountUserInfoResponseBody,
) GoogleAccountUserInfoResponse {
	var googleAccountUserInfoRequestsResponse GoogleAccountUserInfoResponse

	googleAccountUserInfoRequestsResponse.GoogleID = googleAccountUserInfoRequestsResponseBody.GoogleID
	googleAccountUserInfoRequestsResponse.EmailAddress = googleAccountUserInfoRequestsResponseBody.EmailAddress
	googleAccountUserInfoRequestsResponse.VerifiedEmail = googleAccountUserInfoRequestsResponseBody.VerifiedEmail
	googleAccountUserInfoRequestsResponse.FullName = googleAccountUserInfoRequestsResponseBody.FullName
	googleAccountUserInfoRequestsResponse.FirstName = googleAccountUserInfoRequestsResponseBody.FirstName
	googleAccountUserInfoRequestsResponse.LastName = googleAccountUserInfoRequestsResponseBody.LastName
	googleAccountUserInfoRequestsResponse.Picture = googleAccountUserInfoRequestsResponseBody.Picture
	googleAccountUserInfoRequestsResponse.Locale = googleAccountUserInfoRequestsResponseBody.Locale

	return googleAccountUserInfoRequestsResponse
}
